### ISSUE TITLE
[Feature Request]Support multi-language Quiz

### ISSUE THREAD

**Issue by Quorafind** [ECuiDev/obsidian-quiz-generator#1]
Awesome plugin! 

Because I am not an English native speaker. We can try to add a line into prompt like: `Questions and answers should be given in the original language.`

**Comment by ECuiDev** [comment]
Hello!

Thank you for the kind words. Multi-language support will definitely be the next feature I add :]

**Comment by ECuiDev** [comment]
Hi @Quorafind,

Multi-language support has now been added as part of the latest release. Sorry for the delay, I was planning on waiting until this plugin got approved before adding any new features, but the review is taking much longer than expected.

**Comment by ECuiDev** [comment]
Adding new languages is actually quite easy. I've just been pretty busy lately so I haven't been making many updates. But you can expect support for Greek (and a bunch of other new features) early May.

**Comment by YannMiro** [comment]
> Adding new languages is actually quite easy. I've just been pretty busy lately so I haven't been making many updates. But you can expect support for Greek (and a bunch of other new features) early May.

Oh it's ok. It was indeed easy to find a workaround for this. Thanks :)
