### ISSUE TITLE
3rd-party API support

### ISSUE THREAD

**Issue by Euler23333** [ECuiDev/obsidian-quiz-generator#11]
I wonder know if Quiz Generator will support third-party API?Or it is just suitable for API from official websites?

**Comment by ECuiDev** [comment]
You can customize the API URL for every supported provider if that's what you mean.

**Comment by Euler23333** [comment]
It was probably the incorrect API key I provided yesterday that caused the connection error, but the issue has now been resolved. Thank you for your response! This plugin is very useful for reviewing my notes!

**Comment by ECuiDev** [comment]
No worries and I'm glad you find it useful!
