### ISSUE TITLE
Will the quoted notes be read?

### ISSUE THREAD

**Issue by Euler23333** [ECuiDev/obsidian-quiz-generator#13]
I built an electronic dictionary in Obsidian by creating and writing the words I need to memorize in a markdown file. If my words are referenced in the form of ‘![[]]’, will the plugin read the content of the referenced notes displayed in the markdown file I am currently creating?
<img width="949" alt="截屏2024-09-23 下午6 53 07" src="https://github.com/user-attachments/assets/5610d966-ecac-40c4-a0ef-a5a473b6ddac">
This is a picture shows what I said

**Comment by ECuiDev** [comment]
Not yet, but this is a planned feature. See **Note Links** under Future Releases in the README.

**Comment by Euler23333** [comment]
> Not yet, but this is a planned feature. See **Note Links** under Future Releases in the README.还没有，但这是一个计划中的功能。请参见 README 中未来发布的 **备注链接**。

ok thanks for your reply

**Comment by Euler23333** [comment]
> Not yet, but this is a planned feature. See **Note Links** under Future Releases in the README.
Do you have a way to  send sponsor?I consider sponsoring for your project!

**Comment by Euler23333** [comment]
> > Not yet, but this is a planned feature. See **Note Links** under Future Releases in the README.还没有，但这是一个计划中的功能。请参见 README 中未来发布的 **备注链接**。
Do you have a way to  send sponsor?I consider sponsoring for your project!你有办法发送赞助吗？我考虑为你的项目提供赞助！

**Comment by Euler23333** [comment]
> > Not yet, but this is a planned feature. See **Note Links** under Future Releases in the README.还没有，但这是一个计划中的功能。请参见 README 中未来发布的 **备注链接**。

Do you have a way to  send sponsor?I consider sponsoring for your project!你有办法发送赞助吗？我考虑为你的项目提供赞助！

**Comment by ECuiDev** [comment]
I will probably add a way to sponsor in the future but there isn't anything right now. I really appreciate your kindness though! If you want, you can give the repository a star to show your support for now.

**Comment by Euler23333** [comment]
> I will probably add a way to sponsor in the future but there isn't anything right now. I really appreciate your kindness though! If you want, you can give the repository a star to show your support for now.

ok
