### ISSUE TITLE
Where can I find the embedding model when I'm using Ollama? 

### ISSUE THREAD

**Issue by Michael679089** [ECuiDev/obsidian-quiz-generator#14]
There's nothing in the documentation about it.

**Comment by ECuiDev** [comment]
When you choose Ollama as the provider, there's an `Embedding model` setting which I feel is pretty self-explanatory. Are you referring specifically to how the README doesn't mention embedding models anywhere?

![image](https://github.com/user-attachments/assets/86e32314-e7ee-4c7c-a67f-543f79cbf857)

**Comment by Michael679089** [comment]
Sorry I'm new to this. 

This project's readme doesn't explain how I can put the embedding model for Ollama. I asked in Ollama's discord in general instead, and they gave me a link (which is this: https://ollama.com/search?c=embedding) to be able to search for embedding models I can download, and those works. I opened the terminal and pasted the code which is ollama pull <insert embedding model> and the plugin recognized the embedding model.

That's the time I was finally able to play with your quiz generator plugin. It was good, although it's not that fun like RemNote.

**Comment by Michael679089** [comment]
If anyone here needs to get their embedding models for Ollama it's through this link:

https://ollama.com/search?c=embedding
