### ISSUE TITLE
API support of api2d

### ISSUE THREAD

**Issue by jkjoker** [ECuiDev/obsidian-quiz-generator#2]
I hope to support the API of api2d, just like the text generator plugin. The reason is that having an official OpenAI API is inconvenient.

Here is the official website of api2d:
https://api2d.com/profile

Thank you!

**Comment by ECuiDev** [comment]
I am planning to add more LLM providers to choose from in the future! (I'll also look into api2d).

**Comment by ckt1031** [comment]
It should be treated as "Custom API Host" rather than hard coding this third party API.

**Comment by ECuiDev** [comment]
This feature has been added in 2.0.0.
