### ISSUE TITLE
Quota exceed

### ISSUE THREAD

**Issue by calimbrasti94** [ECuiDev/obsidian-quiz-generator#3]
Nice plugin, unfortunately I can't generate quizzes,even with 1 document that has a token length of 300, using gpt-4. It tells me that I have exceeded the token quota.

**Comment by ECuiDev** [comment]
Which usage tier is your OpenAI account? If your account is the free tier, you can't use GPT-4. You can check your account tier at the bottom of [this page](https://platform.openai.com/account/limits).

**Comment by calimbrasti94** [comment]
ok, perfect, i didn't know it went to sleep if you didn't use the api for a while. it was back to tier free.

i've been looking for a plugin like that for a while. it's cool.

only one feedback i can give you so far, is that; some of the multiple answer options sometimes seem to be too long and get lost left and right in the container. but otherwise it's phenomenal.

i look forward to trying the fill-in-the-blank and matching modes, as well as other models like those provided by groq.

thanks again, and I will definitely support the plugin !!!
________________________________
Da: Edward Cui ***@***.***>
Inviato: lunedì 4 marzo 2024 11:32
A: ECuiDev/obsidian-quiz-generator ***@***.***>
Cc: calimbrasti94 ***@***.***>; Author ***@***.***>
Oggetto: Re: [ECuiDev/obsidian-quiz-generator] Quota exceed (Issue #3)


Which usage tier is your OpenAI account? If your account is the free tier, you can't use GPT-4. You can check your account tier at the bottom of this page<https://platform.openai.com/account/limits>.

**Comment by ECuiDev** [comment]
I'm glad you like the plugin and thank you for the support!

As for multiple choice options getting lost in the UI, would it be possible for you to attach an image showing what you mean?

**Comment by calimbrasti94** [comment]
other examples..

[cid:976d8f42-abd9-44f9-bb6f-c18fd1234fdd]
________________________________
Da: lorenzo leone ***@***.***>
Inviato: lunedì 4 marzo 2024 12:27
A: ECuiDev/obsidian-quiz-generator ***@***.***>
Oggetto: R: [ECuiDev/obsidian-quiz-generator] Quota exceed (Issue #3)

maybe i have over complicated the meaning, simply the answer boxes don't contain (they don't wrap, or anything else) the full answer, but just centering the text, thus losing part of the answer. as you see in the image, it is a short answer test, so it seems to happen with other modalities besides MCQ.

for more background; I study biology and am Italian, so the length of the answers I get is also by linguistic necessity, and argumentation, longer.


[cid:72cdfd6a-9f30-4c23-abc8-8b1f543eb993]
________________________________
Da: Edward Cui ***@***.***>
Inviato: lunedì 4 marzo 2024 12:15
A: ECuiDev/obsidian-quiz-generator ***@***.***>
Cc: calimbrasti94 ***@***.***>; Author ***@***.***>
Oggetto: Re: [ECuiDev/obsidian-quiz-generator] Quota exceed (Issue #3)


I'm glad you like the plugin and thank you for the support!

As for multiple choice options getting lost in the UI, would it be possible for you to attach an image showing what you mean?

**Comment by ECuiDev** [comment]
All I see is the CID (Content ID) instead of the actual image. Perhaps try attaching them through the GitHub website instead of replying to the notification email?

**Comment by calimbrasti94** [comment]
sorry, here are the images sent earlier.

![image](https://github.com/ECuiDev/obsidian-quiz-generator/assets/79490114/6a47ceff-ff79-4dc5-8339-c32231cbe17d)

![image](https://github.com/ECuiDev/obsidian-quiz-generator/assets/79490114/30f8b8ee-7265-47ae-a1a6-475d5c8661e7)

**Comment by ECuiDev** [comment]
Hmm, that's strange. When I try with a pretty long question my text wraps around just fine. It still works even after I translate it to Italian.

Could you show the raw text for your questions in source mode? The plugin is a bit picky with question formatting.

![example](https://github.com/ECuiDev/obsidian-quiz-generator/assets/37892357/0162a37a-78ac-406a-9169-7d3792eebe7a)
![example2](https://github.com/ECuiDev/obsidian-quiz-generator/assets/37892357/39ab28d1-e439-4380-b0a3-37fc0674fabd)

**Comment by calimbrasti94** [comment]
here is a video of the text from which he generated the answers, I hope I understand the request. 

also, for more background, i use the "minimal" theme by kepano, i don't know if it can be useful information.

https://github.com/ECuiDev/obsidian-quiz-generator/assets/79490114/2c87ea7e-badf-4278-b622-03b92c2bd24f

**Comment by ECuiDev** [comment]
Ah, I meant the text of the actual questions (you'll need to save the generated questions), not the text the questions were generated from.

For example, the text of the two questions I sent earlier (saved in callout format) is

```
> [!question] In the realm of artificial intelligence ethics, consider the development of autonomous weapon systems (AWS). Advocates argue that AWS can minimize human casualties in warfare, while critics express concerns about the lack of human control and potential ethical implications. Applying an ethical framework, which option aligns with a consequentialist perspective?
> a) Reject the use of AWS to preserve human control and uphold moral principles.
> b) Implement strict regulations and oversight to balance the benefits and risks of AWS.
> c) Embrace AWS deployment to reduce overall casualties and enhance military effectiveness.
> d) Encourage international collaboration to establish a global consensus on AWS usage.
>> [!success]- Answer
>> c) Embrace AWS deployment to reduce overall casualties and enhance military effectiveness.

> [!question] Nel campo dell'etica dell'intelligenza artificiale, consideriamo lo sviluppo di sistemi d'arma autonomi (AWS). I sostenitori sostengono che AWS può ridurre al minimo le vittime umane in guerra, mentre i critici esprimono preoccupazione per la mancanza di controllo umano e le potenziali implicazioni etiche. Applicando un quadro etico, quale opzione si allinea con una prospettiva consequenzialista?
> a) Rifiutare l'uso di AWS per preservare il controllo umano e sostenere i principi morali.
> b) Implementare normative e controlli rigorosi per bilanciare i vantaggi e i rischi di AWS.
> c) Adottare l'implementazione di AWS per ridurre le vittime complessive e migliorare l'efficacia militare.
> d) Incoraggiare la collaborazione internazionale per stabilire un consenso globale sull'utilizzo di AWS.
>> [!success]- Risposta
>> c) Adottare l'implementazione di AWS per ridurre le vittime complessive e migliorare l'efficacia militare.
```

**Comment by calimbrasti94** [comment]
ahah, i knew i was doing it wrong, sorry. here is the raw text generated in callout format. 

more info: at the time of generation i had simultaneously activated both the option to save questions in spaced repetition format and in callout. in the text pasted below i selected only the callout format, but for spaced it was same text with different organization (obviously).


> [!question] Cosa indica il termine 'biodisponibilità' nei farmaci?
> a) La quantità di farmaco eliminato attraverso la bile
> b) La frazione inalterata di farmaco presente nella circolazione sanguigna
> c) La capacità di un farmaco di alterare l'appetito
> d) La velocità con cui un farmaco è assorbito dal tratto gastrointestinale
>> [!success]- Answer
>> b) La frazione inalterata di farmaco presente nella circolazione sanguigna

> [!question] Cosa accade a livello molecolare quando il succo di pompelmo interagisce con certi farmaci?
>> [!success]- Answer
>> Il succo di pompelmo inibisce in maniera selettiva una specifica isoforma del citocromo P450 del tratto gastrointestinale, aumentando così la biodisponibilità di alcuni farmaci metabolizzati da questa isoforma.

> [!question] Il succo di pompelmo può inattivare un'isoforma del citocromo P450.
> True or false?
>> [!success]- Answer
>> True

> [!question] Qual è l'effetto del consumo di alimenti contenenti tiramina in pazienti che assumono MAOI?
>> [!success]- Answer
>> Il consumo di alimenti contenenti tiramina in pazienti che assumono MAOI può portare a un accumulo di tiramina, che promuove il rilascio di grandi quantità di catecolamine e può causare una crisi ipertensiva.

**Comment by ECuiDev** [comment]
Hmm, that's weird. I pasted your questions into a new note and they get displayed properly.

![Example2](https://github.com/ECuiDev/obsidian-quiz-generator/assets/37892357/1bcc583a-12a0-4e42-a41b-62501f2a917c)
![Example1](https://github.com/ECuiDev/obsidian-quiz-generator/assets/37892357/62b36f38-a489-4c4f-852d-d10751c62ce7)

**Comment by calimbrasti94** [comment]
could it be a theme compatibility issue? i have modified several things in the theme granularly, i don't know if it could adversely affect the UI of your plugin.

**Comment by ECuiDev** [comment]
Yup, that was it. I just installed Minimal and now my question text isn't wrapping either. Some of my CSS styles are probably being overridden by Minimal somewhere. I'll see if I can find a fix.

**Comment by ECuiDev** [comment]
This bug has been fixed as part of the next release.
