### ISSUE TITLE
Not able to open self made quiz

### ISSUE THREAD

**Issue by Dragonslayersakata** [ECuiDev/obsidian-quiz-generator#6]
Hello, I really like the idea of this add-on. I am making quizzes from question banks I have received via textbooks. The issue is this: after I format the questions according to the syntax in the .md file, I select "Open Quiz from this note" & am greeted with a blank quiz. I have followed the syntax correctly because the interactive answer button is shown. Is there something else I need to do?

**Comment by ECuiDev** [comment]
Can you send a picture of what you see when you select "Open Quiz from this note", and the text of a question you're trying to open?

**Comment by Dragonslayersakata** [comment]
Hello, this is what I get:
![image](https://github.com/ECuiDev/obsidian-quiz-generator/assets/14871598/a2391c87-5c99-472c-90b4-f8c689ff1020)

**Comment by ECuiDev** [comment]
Oh, I see. There's 2 problems here.

1. Your question format is incorrect. Below is an example of how a multiple choice question in callout format must look. You can learn more about how questions must be formatted [here](https://github.com/ECuiDev/obsidian-quiz-generator#question-formatting).
```
> [!question] In the realm of artificial intelligence ethics, consider the development of autonomous weapon systems (AWS). Advocates argue that AWS can minimize human casualties in warfare, while critics express concerns about the lack of human control and potential ethical implications. Applying an ethical framework, which option aligns with a consequentialist perspective?
> a) Reject the use of AWS to preserve human control and uphold moral principles.
> b) Implement strict regulations and oversight to balance the benefits and risks of AWS.
> c) Embrace AWS deployment to reduce overall casualties and enhance military effectiveness.
> d) Encourage international collaboration to establish a global consensus on AWS usage.
>> [!success]- Answer
>> c) Embrace AWS deployment to reduce overall casualties and enhance military effectiveness.
```

2. Multiple choice questions must have 4 choices (your question has 5). Support for more than 4 choices will be added in a future update.

**Comment by Dragonslayersakata** [comment]
Okay, so I deleted one of the answer choices, making it 4 answer choices & it works! Thanks for the help! Any idea when the support would come out? Also, is there anywhere to donate to you?

**Comment by ECuiDev** [comment]
Glad I could help!

As for when support for more than 4 choices will come out, the absolute latest would be the end of April. But ideally it'll be out sometime in the next 2 weeks.

Also, it's very kind of you to want to donate. I don't have a Buy Me a Coffee or anything set up, but if you'd still like to support me consider giving the repository a star :]
