### ISSUE TITLE
Unable to use keyboard shortcut when modal UI is open

### ISSUE THREAD

**Issue by calimbrasti94** [ECuiDev/obsidian-quiz-generator#7]
Hello @ECuiDev,

using the plugin I have noticed that it makes it impossible to use keyboard shortcuts when the modal UI is open (in my case, I have 'ctrl+s' to lint the file with the “linter” plugin, when the UI is open I can't, as well as other shortcuts), or, the “Hover” plugin doesn't even work in a second open Obisdian window when the UI is active in another window. Also, it would be very convenient if the UI did not prevent interacting with the file but could behave like the “Hover” plugin windows.

lastly (I didn't want to open another issue for this), on Android, the UI's “answer box” fails to include “short-answers” that are too long and cuts out some text, also preventing scrolling to continue reading.

Thank you very much for this plugin, I use it every day ! hope I was helpful.

**Comment by ECuiDev** [comment]
Hi,

Regarding the keyboard shortcuts and the Hover plugin not working in a second Obsidian window, I'm pretty sure this is a consequence of Obsidian's Modal class, but I'll see what I can do.

As for the UI not preventing interaction with the file, what do you mean by interaction? Do you mean being able to move the modal around like in this [demo video](https://github.com/nothingislost/obsidian-hover-editor?tab=readme-ov-file#demo) from the Hover Editor plugin?

Lastly, are you using any themes on Android? Certain themes seem to interfere with text overflow which I'm already working on a fix for. If you could attach a screenshot of what you're seeing that would be greatly appreciated.

**Comment by ECuiDev** [comment]
Hi,

I'm closing this issue as the keyboard shortcut and mobile text cutoff issues have been fixed and will be included in the next release.

Making the UI behave like the Hover plugin turns out to be pretty complex so I've marked it as a feature to be included in a future update.
